export const GET_PARTS = 'GET PARTS';
export const OPEN_ADD_FORM = 'ADD NEW PARTS';



export const GET_SUPPLIERS = 'GET SUPPLIERS';
export const OPEN_ADD_SUPPLIER_FORM = 'ADD NEW SUPPLIER';
export const ADD_SUPPLIER ='ADD SUPPLIER';
export const DEL_SUPPLIER = 'DELETE SUPPLIER';
export const OPEN_DEL_SUPPLIER_MODAL = 'DELETE SUPPLIER MODAL'
